---
title: ""
message: false
warning: false
---

# Packages
```{r}
library(dplyr)
library(gsheet)
library(tidyverse)
library(writexl)
library(patchwork)
gc()
```

```{r, warning=FALSE, message=FALSE}
#data2 = gsheet2tbl("https://docs.google.com/spreadsheets/d/1NZJYstoltlN18XhS1g4Om6laTYnHCgqwdiJ-GutUaYk/edit?usp=sharing")

data2 = gsheet2tbl("https://docs.google.com/spreadsheets/d/1D8LV8R8WalqyheeT6XlSQkoYRg5K1Rp2-fCktx3nkro/edit?usp=sharing")

camila = gsheet2tbl("https://docs.google.com/spreadsheets/d/1zX-6_nGgKGZH8DBTxBpnoYX_xzM0cINBViJLXkK5hV4/edit?usp=sharing")

data2

data2$plot_moist = data2$plot_moist/100
data2$plot_weight = data2$plot_weight/100
#data2$SB = data2$SB*10

data22 = data2 %>%
  filter(!is.na(SB)) %>% 
  filter(!is.na(yield_lb)) %>% 
 dplyr::mutate(
    trt = factor(trt), 
        # weig_12 = tw*((100 - plot_moist)/88), 
         yld = plot_weight/(80/43560), 
         kg_ha = yld*1.2085) %>% 
  filter(!kg_ha <=4000)

data22$year = as.factor(data22$year)
data22$blk = as.factor(data22$blk)
data22$trial = as.factor(data22$trial)
```

```{r}
data222 = data22  %>%
  #filter(!year == "2025") %>% 
  
  #filter(!trial %in% c("25-P2S1_VAR2","25-P2S2_PC2")) %>% 
 # filter(!is.na(SB_1)) %>% 
  select(year,trial,gen,trt,plot,blk,SB,kg_ha)


camila$kg_ha = camila$kg_ha*1000

camila$SB = camila$SB/100

camila = camila %>% 
  select(year,trial,gen,trt,plot,blk,SB,kg_ha)


camila$year = as.factor(camila$year)
camila$blk = as.factor(camila$blk)
camila$trial = as.factor(camila$trial)

data222 = rbind(camila,data222)
data222

```

```{r}

library(lme4)

tt <- lmer(
  kg_ha ~ SB +
    (1 + SB | gen) +
    (1|trial/blk), data = data222)



re <- ranef(tt)$gen

damage_coef <- data.frame(
  gen = rownames(re),
  intercept = fixef(tt)[1] + re[, "(Intercept)"],
  damage_coef = fixef(tt)["SB"] + re[, "SB"]
)



```

```{r}

overall_regression = data22 |> 
 ggplot(aes(SB, y = yld)) +
  geom_point(color = "NA")+
  scale_y_continuous(breaks = c(5000,6000,7000,8000,9000,
                      10000,11000,12000,13000,14000), 
                     limits = c(5000, 14000))+
 scale_x_continuous(breaks = c(0,10,20,30,40,50,60,70,80,90,100),
                    limits = c(0, 100))+
  geom_abline(aes(intercept = 8238.7285, slope = -371.4572),
              size = 1, fill = "black", color = "black", linetype = 2)+
  geom_abline(aes(intercept = 10281.71,slope = -326.32) ,
              size = 2)+
  geom_abline(aes(intercept = 12322.5967,slope = -281.3444), size = 1, linetype = 2)+
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "SB index", y = "Yield (kg/ha) ")

overall_regression
```

```{r}
set.seed(123)

damage_coef2 = damage_coef %>% 
  select(damage_coef,gen)


damage_coef2 = damage_coef2 %>% 
  filter(!damage_coef >= 0)


dados_dummy <- model.matrix(~ gen - 1, data = damage_coef2)

set.seed(123)
dados_preparados <- cbind(dados_dummy, DC = damage_coef2$damage_coef)

set.seed(123)
resultado_kmeans <- kmeans(dados_preparados, centers = 3)

library(factoextra)

p = fviz_cluster(resultado_kmeans, data = dados_preparados, label = NULL,geom = "point",pointsize = 3, shape = 20)
p2 = p +
  scale_color_manual(values = c('#9ccb86','#cf597e','steelblue'))+
  scale_fill_manual(values = c('#9ccb86','#cf597e','steelblue'))+
  theme(
    axis.title = element_text(size = 14, face = "bold"),  
    axis.text = element_text(size = 12)) + 
  labs(
    title = "",  
    x = "PC1",  
    y = "PC2")+
  theme(legend.position = "none")
p2

```
# Regression

```{r}
damage_coef2$Cluster <- resultado_kmeans$cluster

c_01 = damage_coef2 %>% 
  filter(Cluster == 1)

c_02 = damage_coef2 %>% 
  filter(Cluster == 2) #%>% 
  #filter(!gen %in% c("212M1144","CLHA02","DG353M","24AR1111","CLL16","Ozark","RT7301",
                  #   "24AR1134","RU2102186"))

c_03 = damage_coef2 %>% 
  filter(Cluster == 3)


#tt2 = lmer(kg_ha ~ SB + (1|year/trial), data = c1)

```

## Group 1
```{r}
data_r1 = data222 %>% 
  filter(gen %in% c_01$gen)


#data_r1$SB = data_r1$SB*100

model_r1 <- lmer(
  kg_ha ~ SB +
    (1 + SB) +
    (1|year/trial), data = data_r1)
```

```{r}
mean(data_r1$SB)
```


```{r}
summary(model_r1)
confint(model_r1)
```


## Group 2
```{r}
data_r2 = data222 %>% 
  filter(gen %in% c_02$gen)



model_r2 <- lmer(
  kg_ha ~ SB +
    (1 + SB) +
    (1|year/trial), data = data_r2)
```

```{r}
mean(data_r2$SB)
```

```{r}
summary(model_r2)
confint(model_r2)
```

## Group 3
```{r}
data_r3 = data222 %>% 
  filter(gen %in% c_03$gen)



model_r3 <- lmer(
  kg_ha ~ SB +
    (1 + SB) +
    (1|year/trial), data = data_r3)

```

```{r}
mean(data_r3$SB)
```


```{r}
summary(model_r3)
confint(model_r3)
```

# Economic losses

## Group 1

```{r}


set.seed(123)
sev = seq(0, 9,length.out = 100)
yld = seq(4000, 16000,length.out = 100)
b1 <- runif(100,min = 159.97, max = 430.21)
price_rice <- seq(300, 600,length.out = 10)

combined_data_g1 <- expand.grid(sev = sev, yld = yld, b1 = b1,price_rice = price_rice)


ylmer_simu_g1 = combined_data_g1 %>% 
  mutate(loss =((((((b1/11142.94)*sev)*100)*yld)/100)/1000)*price_rice)

ylmer_simu_g1$group = "Group 1"
ylmer_simu_g1$b0 = 11142.94


gc()
```

## Group 2


```{r}
#sev  = data.frame(sev = seq(20,100, by = 10))
#yield = data.frame(yld = seq(4000,16000,by = 2000))

#combined_data <- expand.grid(sev = sev$sev, yld = yield$yld)

set.seed(123)
sev = seq(0, 9,length.out = 100)
yld = seq(4000, 16000,length.out = 100)
b1 <- runif(100,min = 192.59, max = 376.04)
price_rice <- seq(300, 600,length.out = 10)

combined_data_g2 <- expand.grid(sev = sev, yld = yld, b1 = b1,price_rice = price_rice)


ylmer_simu_g2 = combined_data_g2 %>% 
  mutate(loss =((((((b1/9945.61)*sev)*100)*yld)/100)/1000)*price_rice)

ylmer_simu_g2$group = "Group 2"
ylmer_simu_g2$b0 = 9945.61

gc()
```

## Group 3


```{r}
#sev  = data.frame(sev = seq(20,100, by = 10))
#yield = data.frame(yld = seq(4000,16000,by = 2000))

#combined_data <- expand.grid(sev = sev$sev, yld = yield$yld)

set.seed(123)
sev = seq(0, 9,length.out = 100)
yld = seq(4000, 16000,length.out = 100)
b1 <- runif(100,min = 567.31, max = 796.82)
price_rice <- seq(300, 600,length.out = 10)

combined_data_g3 <- expand.grid(sev = sev, yld = yld, b1 = b1,price_rice = price_rice)


ylmer_simu_g3 = combined_data_g3 %>% 
  mutate(loss =((((((b1/12368.25)*sev)*100)*yld)/100)/1000)*price_rice)

ylmer_simu_g3$group = "Group 3"
ylmer_simu_g3$b0 = 12368.25


gc()
```

```{r}
ylmer_simu_all = rbind(ylmer_simu_g1,ylmer_simu_g2,ylmer_simu_g3)
ylmer_simu_all
```

```{r}
heat_loss = ylmer_simu_all %>%
  ggplot(aes(sev, yld, fill = loss)) +
  geom_raster() +
  scale_x_continuous(breaks = seq(0, 9, by = 1),
                     expand = c(0.02,0.02)) +
  scale_y_continuous(breaks = seq(4000, 16000, by = 2000),
                     expand = c(0.02,0.02)) +
  
  scale_fill_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 5,             # number of steps (adjust for contrast)
    breaks = seq(0, 3000, 500),
    name = "L (USD/ha)",
    
guide = guide_colorsteps(
    keyheight = unit(150, "pt")   # << AQUI aumenta a altura da legenda
  )
) +
  facet_wrap(~group, ncol =1)+
  theme_bw() +
  labs(
    y = "Attainable yield (kg/ha)",
    x = "SB index"
  ) +
  theme(
    text = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"),
    strip.text = element_text(size = 14,face = "bold"),
    axis.text.x = element_text(vjust = 1),
    legend.position = "right",
    legend.box = "horizontal",
    panel.grid = element_blank(),
    strip.background = element_blank()
  )

gc()
 
 heat_loss
```


```{r}
median(data_r1$yld)
median(data_r1$SB)

median(data_r2$SB)

median(data_r3$SB)

median(data222$SB)
```

```{r}

ylmer_simu_min2 = ylmer_simu_all %>% 
  group_by(group) %>% 
  #mutate(loss =((((((b1/b0)*sev)*100)*yld)/100)/1000)) %>%
  mutate(loss =((((((b1/b0)*sev)*100)*yld)/100)/1000)*price_rice) %>% 
  group_by(group) %>% 
   mutate(pressure = case_when(sev > median(sev) ~ "High pressure",
                           sev <= median(sev) ~"Low pressure"),
          attainable = case_when(yld > median(yld) ~ "High yield",
                                 yld <= median(yld) ~"Low yield"))
         

```


```{r}
ylmer_simu_min2 %>% 
  ggplot(aes(pressure,loss))+
  geom_boxplot(na.rm = F)
```

```{r}
simu_summary <- ylmer_simu_min2 %>%
  group_by(group,pressure,attainable) %>%
  summarise(
    mean_loss = mean(loss, na.rm = TRUE),
    ci_low = quantile(loss, 0.025),
    ci_high = quantile(loss, 0.975),
    .groups = "drop"
  )
```

```{r}
pressure_cols <- c(
  "High pressure"  = "#6F3F1F",
  "Low pressure" = "#2E8B57")

```


```{r}

library(ggplot2)
library(dplyr)
library(scales)   

dodge_w <- 0.45   # mantenha o mesmo valor usado nas outras camadas

interval2 <- ylmer_simu_min2 %>% 
  ggplot(aes(x = pressure, y = loss)) +
  
  # Intervalos (médias + IC) lado a lado por attainable
  geom_pointrange(
    data = simu_summary,
    aes(
      x        = pressure,
      y        = mean_loss,
      ymin     = ci_low,
      ymax     = ci_high,
      color    = pressure,
      linetype = attainable,
      group    = attainable
    ),
    position = position_dodge(width = dodge_w),
    size = 1.0
  ) +
  
  # Ponto da média (opcional)
  geom_point(
    data = simu_summary,
    aes(
      x     = pressure, 
      y     = mean_loss,
      color = pressure,
      shape = attainable,
      group = attainable
    ),
    position = position_dodge(width = dodge_w),
    size = 2.2
  ) +
  
  # Texto da média alinhado ao seu respectivo intervalo (lado a lado)
  geom_text(
    data = simu_summary,
    aes(
      x     = pressure,
      y     = ci_high,  # posiciona o rótulo próximo à ponta superior do IC
      # Opção 1 (base R):
      label = sprintf("%.2f", mean_loss),
      # Opção 2 (scales): label = number(mean_loss, accuracy = 0.01),
      color = pressure,
      group = attainable
    ),
    position   = position_dodge(width = dodge_w),
    nudge_x    = 0.08,    # -> direita (ajuste fino conforme seu espaçamento)
    nudge_y    = 0.08,       # pequeno empurrão para não colar na barra
    hjust      = -0.1,          # à direita; ajuste conforme preferir
    vjust      = 1,       # ligeiramente acima da ponta do intervalo
    size       = 4,
    fontface   = "bold.italic"
    #, check_overlap = TRUE   # opcional para evitar sobreposição
  ) +
  
  # Escalas
  scale_color_manual(values = pressure_cols, name = "Pressure") +
  scale_linetype_manual(values = c("Low yield" = "solid", "High yield" = "dashed"),
                        name = "Attainable") +
  scale_shape_manual(values = c("Low yield" = 16, "High yield" = 17),
                     name = "Attainable") +
  facet_wrap(~group, ncol = 1)+
  theme_bw() +
  labs(
    x = "Pressure level",
    y = "Economic losses (kg/ha)"
  ) +
  theme(
    text = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"),
    strip.text = element_text(size = 14,face = "bold"),
    axis.text.x = element_text(vjust = 1),
    legend.position = "none",
    legend.box = "horizontal",
    strip.background = element_blank()
  )
  
  
interval2

```


```{r}
library(cowplot)
base_plot <- (interval2 | heat_loss) +
  plot_layout(guides = "collect")


base_grob <- patchworkGrob(base_plot)



final_plot <- ggdraw(base_grob) +
  draw_plot_label(
    label = c("(a)", "(b)"),
    x     = c(0, 0, 0.46), 
    y     = c(1, 0.5, 1),   
    size  = 18,                    
    fontface = "bold"
  )


final_plot


ggsave("fig/ec_losses.png", bg = "white", dpi = 600, height = 6, width = 10)

gc()
```

# Economic damage threshold

## Group 1


```{r}
# Function to Simulate EDC
set.seed(123)

simula_LDE <- function(n, media_rp, sd_rp, eficacia, cd_base, custo_range, preco_range) {
  simulacoes <- tibble(
    rendimento_potencial = rnorm(n, media_rp, sd_rp),
    custo_controle = runif(n, custo_range[1], custo_range[2]),
    preco_produto = runif(n, preco_range[1], preco_range[2]),
    eficacia = eficacia
  ) %>% 
    mutate(
      cd_base = cd_base,
      coeficiente_dano = cd_base * rendimento_potencial,
      LDE = (custo_controle / (preco_produto * coeficiente_dano)) * eficacia
    )
  return(simulacoes)
}


n = 50000 # number of simulations
media_rp = 11.14 # in ton/ha
sd_rp = 0.70  # SD of attainable yield
eficacia = rnorm(50000, 0.54, 0.1) #  in proportion
cd_base = 0.02
custo_range = c(40, 160) # cust of control (US$)
preco_range = c(100, 600) # soybean price (US$)

# run the simulation
simula_g1 <- simula_LDE(n, media_rp, sd_rp, eficacia, cd_base, custo_range, preco_range)
```

```{r}
edt_g1 = simula_g1 |> 
  ggplot(aes(rendimento_potencial, eficacia, 
             color = LDE, size = coeficiente_dano))+
  geom_point()+
  #scale_color_viridis_c(labels = scales::number_format(accuracy = 0.1))+
    scale_colour_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 6,             # number of steps (adjust for contrast)
    breaks = seq(0, 8, 1),
    name = "EDT",
    guide = guide_legend(
    override.aes = list(size = 6)   
  )
) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25)) +
   labs(color = "EDT",
     x = "Attainable yield (ton/ha)",
       y = "Fungicide efficacy (%)",
     size = "DC")+
  theme_bw()+
    theme(
    legend.position = "top",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 18,face = "bold"),
    axis.title = element_text(size = 18, face = "bold")
  )

edt_g1
```


```{r}
min(simula_g1$LDE)
mean(simula_g1$LDE)
```

```{r}
library(ggdist) 
edt_density_g1 <- ggplot(simula_g1, aes(x = LDE)) +
  stat_halfeye(fill = "#7FBF7B", alpha = 0.7) +
  geom_vline(aes(xintercept = median(LDE)), color = "#6F3F1F", linetype = "dashed", size = 1) +
 # annotate("text", x = 0.6, y = 0.90, label = "Median = 1.54%", color = "black", size = 4.5) +
  #annotate("text", x = 0.6, y = 0.80, label = "95% CI = 0.89%, 2.53%", color = "black", size = 4.5) +
  labs(
    x = "Economic Damage Threshold (EDT)",
    y = "Density"
  ) +
  theme_bw()+
    theme(
    legend.position = "right",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 18,face = "bold"),
    axis.title = element_text(size = 18, face = "bold")
  )

edt_density_g1
```
## Group 2

```{r}
# Function to Simulate EDC
set.seed(123)

simula_LDE <- function(n, media_rp, sd_rp, eficacia, cd_base, custo_range, preco_range) {
  simulacoes <- tibble(
    rendimento_potencial = rnorm(n, media_rp, sd_rp),
    custo_controle = runif(n, custo_range[1], custo_range[2]),
    preco_produto = runif(n, preco_range[1], preco_range[2]),
    eficacia = eficacia
  ) %>% 
    mutate(
      cd_base = cd_base,
      coeficiente_dano = cd_base * rendimento_potencial,
      LDE = (custo_controle / (preco_produto * coeficiente_dano)) * eficacia
    )
  return(simulacoes)
}


n = 50000 # number of simulations
media_rp = 9.9 # in ton/ha
sd_rp = 0.70  # SD of attainable yield
eficacia = rnorm(50000, 0.54, 0.1) #  in proportion
cd_base = 0.02
custo_range = c(40, 160) # cust of control (US$)
preco_range = c(100, 600) # soybean price (US$)

# run the simulation
simula_g2 <- simula_LDE(n, media_rp, sd_rp, eficacia, cd_base, custo_range, preco_range)
```

```{r}
edt_g2 = simula_g2 |> 
  ggplot(aes(rendimento_potencial, eficacia, 
             color = LDE, size = coeficiente_dano))+
  geom_point()+
  #scale_color_viridis_c(labels = scales::number_format(accuracy = 0.1))+
    scale_colour_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 6,             # number of steps (adjust for contrast)
    breaks = seq(0, 8, 1),
    name = "EDT",
    guide = guide_legend(
    override.aes = list(size = 6)   
  )
) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25)) +
   labs(color = "EDT",
     x = "Attainable yield (ton/ha)",
       y = "Fungicide efficacy (%)",
     size = "DC")+
  theme_bw()+
    theme(
    legend.position = "top",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 18,face = "bold"),
    axis.title = element_text(size = 18, face = "bold")
  )

edt_g2
```


```{r}
min(simula_g2$LDE)
mean(simula_g2$LDE)
```

```{r}
library(ggdist) 
edt_density_g2 <- ggplot(simula_g2, aes(x = LDE)) +
  stat_halfeye(fill = "#7FBF7B", alpha = 0.7) +
  geom_vline(aes(xintercept = median(LDE)), color = "#6F3F1F", linetype = "dashed", size = 1) +
 # annotate("text", x = 0.6, y = 0.90, label = "Median = 1.54%", color = "black", size = 4.5) +
  #annotate("text", x = 0.6, y = 0.80, label = "95% CI = 0.89%, 2.53%", color = "black", size = 4.5) +
  labs(
    x = "Economic Damage Threshold (EDT)",
    y = "Density"
  ) +
  theme_bw()+
    theme(
    legend.position = "right",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 18,face = "bold"),
    axis.title = element_text(size = 18, face = "bold")
  )

edt_density_g2
```
## Group 3

```{r}
# Function to Simulate EDC
set.seed(123)

simula_LDE <- function(n, media_rp, sd_rp, eficacia, cd_base, custo_range, preco_range) {
  simulacoes <- tibble(
    rendimento_potencial = rnorm(n, media_rp, sd_rp),
    custo_controle = runif(n, custo_range[1], custo_range[2]),
    preco_produto = runif(n, preco_range[1], preco_range[2]),
    eficacia = eficacia
  ) %>% 
    mutate(
      cd_base = cd_base,
      coeficiente_dano = cd_base * rendimento_potencial,
      LDE = (custo_controle / (preco_produto * coeficiente_dano)) * eficacia
    )
  return(simulacoes)
}


n = 50000 # number of simulations
media_rp = 12.36 # in ton/ha
sd_rp = 0.70  # SD of attainable yield
eficacia = rnorm(50000, 0.54, 0.1) #  in proportion
cd_base = 0.05
custo_range = c(40, 160) # cust of control (US$)
preco_range = c(100, 600) # soybean price (US$)

# run the simulation
simula_g3 <- simula_LDE(n, media_rp, sd_rp, eficacia, cd_base, custo_range, preco_range)
```

```{r}
edt_g3 = simula_g3 |> 
  ggplot(aes(rendimento_potencial, eficacia, 
             color = LDE, size = coeficiente_dano))+
  geom_point()+
  #scale_color_viridis_c(labels = scales::number_format(accuracy = 0.1))+
    scale_colour_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 6,             # number of steps (adjust for contrast)
    breaks = seq(0, 8, 1),
    name = "EDT",
    guide = guide_legend(
    override.aes = list(size = 6)   
  )
) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.25)) +
   labs(color = "EDT",
     x = "Attainable yield (ton/ha)",
       y = "Fungicide efficacy (%)",
     size = "DC")+
  theme_bw()+
    theme(
    legend.position = "top",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 18,face = "bold"),
    axis.title = element_text(size = 18, face = "bold")
  )

edt_g3
```


```{r}
min(simula_g3$LDE)
mean(simula_g3$LDE)
```

```{r}

edt_density_g3 <- ggplot(simula_g3, aes(x = LDE)) +
  stat_halfeye(fill = "#7FBF7B", alpha = 0.7) +
  geom_vline(aes(xintercept = median(LDE)), color = "#6F3F1F", linetype = "dashed", size = 1) +
 # annotate("text", x = 0.6, y = 0.90, label = "Median = 1.54%", color = "black", size = 4.5) +
  #annotate("text", x = 0.6, y = 0.80, label = "95% CI = 0.89%, 2.53%", color = "black", size = 4.5) +
  labs(
    x = "Economic Damage Threshold (EDT)",
    y = "Density"
  ) +
  theme_bw()+
    theme(
    legend.position = "right",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 18,face = "bold"),
    axis.title = element_text(size = 18, face = "bold")
  )

edt_density_g3
```

```{r}

library(ggplot2)
library(patchwork)
library(cowplot)

base_plot <- (edt_g1 / edt_g2 / edt_g3 | edt_density_g1 / edt_density_g2 / edt_density_g3) +
  plot_layout(guides = "collect") +
  plot_annotation(
    theme = theme(
      legend.position      = "top",
      legend.justification = "center",
      legend.box.just      = "center"
    )
  ) &
  guides(
    colour = guide_legend(override.aes = list(size = 6)),
    size   = guide_legend()
  )


base_grob <- patchworkGrob(base_plot)

final_plot <- ggdraw(base_grob) +
  draw_plot_label(
    label = c("(a)", "(b)", "(c)"),
    x     = c(0.01, 0.01, 0.50),
    y     = c(0.92, 0.45, 0.92),
    size  = 14,
    fontface = "bold",
    hjust = 0
  )

final_plot


```

```{r}
ggsave("fig/EDT.png", bg = "white", dpi = 600, height = 6, width = 10)
```

## All groups
```{r}
simula_g1$group = "Group 1"
simula_g2$group = "Group 2"
simula_g3$group = "Group 3"

simu_all = rbind(simula_g1,simula_g2, simula_g3)
```


```{r}

# GROUP 1

set.seed(123)

DC_g1 <- 0.02
price_rice <- seq(300, 600,length.out = 200)
cost <- seq(40, 160,length.out = 200)
lambda = seq(0.40, 0.80,length.out = 200)

combined_data_g1 <- expand.grid(lambda = lambda, price_rice = price_rice,
                             cost = cost, DC = DC_g1)


EDT_simulated_g1 = combined_data_g1 %>% 
  mutate(EDT = (cost/(price_rice*DC))*lambda)

EDT_simulated_g1$group = "Group 1"
# GROUP 2

DC_g2 <- 0.02

combined_data_g2 <- expand.grid(lambda = lambda, price_rice = price_rice,
                             cost = cost, DC = DC_g2)


EDT_simulated_g2 = combined_data_g2 %>% 
  mutate(EDT = (cost/(price_rice*DC))*lambda)

EDT_simulated_g2$group = "Group 2"

# GROUP 3

DC_g3 <- 0.05

combined_data_g3 <- expand.grid(lambda = lambda, price_rice = price_rice,
                             cost = cost, DC = DC_g3)


EDT_simulated_g3 = combined_data_g3 %>% 
  mutate(EDT = (cost/(price_rice*DC))*lambda)

EDT_simulated_g3$group = "Group 3"

simu_all = rbind(EDT_simulated_g1,EDT_simulated_g2,EDT_simulated_g3)
```

```{r}

heat_EDT_all = simu_all %>%
 # filter(group == "Group 1") %>% 
  filter(EDT <=9) %>% 
  filter(cost <=120) %>% 
  #filter(lambda >= 0.75) %>% 
 # filter(lambda <= 0.76) %>% 
  ggplot(aes(lambda, cost, fill = EDT)) +
  geom_raster() +
  scale_y_continuous(breaks = seq(40, 120, by = 20),
                     expand = c(0.02,0.02)) +
  scale_x_continuous(breaks = seq(0.40, 0.80, by = 0.10),
                     expand = c(0,0)) +
  #scale_y_continuous(breaks = seq(100, 600, by = 100)) +
scale_fill_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 6,             # number of steps (adjust for contrast)
    breaks = seq(0, 8, 1),
    name = "EDT",
    guide = guide_legend(
    override.aes = list(size = 6)   
  )
) +
  facet_wrap(~group, ncol = 1)+
  
  theme_bw() +
  labs(
    y = "Price (USD/ha)",
    x = "Control efficacy (%)"
  ) +
  theme(
    text = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"),
    strip.text = element_text(size = 14,face = "bold"),
    axis.text.x = element_text(vjust = 1),
    legend.position = "right",
    panel.grid = element_blank(),
    strip.background = element_blank()
  )
 
 heat_EDT_all
```


```{r}

edt_density_all <- simu_all %>% 
  filter(EDT <=9) %>% 
  filter(cost <=120) %>% 
  ggplot(aes(x = EDT)) +
  stat_halfeye(fill = "#7FBF7B", alpha = 0.7) +
  geom_vline(aes(xintercept = median(EDT)), color = "#6F3F1F", linetype = "dashed", size = 1) +
 # annotate("text", x = 0.6, y = 0.90, label = "Median = 1.54%", color = "black", size = 4.5) +
  #annotate("text", x = 0.6, y = 0.80, label = "95% CI = 0.89%, 2.53%", color = "black", size = 4.5) +
  labs(
    x = "Economic Damage Threshold (EDT)",
    y = "Density"
  ) +
  facet_wrap(~group, ncol = 1)+
  theme_bw()+
    theme(
    legend.position = "right",
    text = element_text(size = 14),
    legend.justification = "center",
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 14,face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    strip.background = element_blank()
  )

edt_density_all
```

```{r}
edt_density_all|heat_EDT_all
```
```{r}
ggsave("fig/EDT2.png", bg = "white", dpi = 600, height = 6, width = 10)

```

# Elasticidade

## Overall
```{r}

library(dplyr)
library(tidyr)

set.seed(123)

b0_sim = seq(4000, 16000,length.out = 400)

#b1_sim <- runif(400,min = 567.31, max = 796.82)
#b1_sim <- runif(400,min = 192.59, max = 376.04)

b1_sim <- runif(400,min = 159.97, max = 796.82)


n <- 50000

S_seq <- 0:9


sim_df <- expand_grid(
    S = S_seq,
    b0 = b0_sim,
    b1 = b1_sim
) %>%
  mutate(
    Y  = b0 + b1 * S,
    Y0 = b0
  )

sim_df
```




```{r}

tradeoff_df <- sim_df %>% 
  mutate(
     B0 = b0,
  DC = b1 / b0,
  B1 = b1
  )

rainbow_dc =  tradeoff_df %>% 
  ggplot(aes(B0,DC, color = B1))+
  geom_jitter()+
  geom_smooth(se = F, color = NA)+
  theme_bw()+
   scale_colour_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 6,             # number of steps (adjust for contrast)
    name = "Slope")+
   labs(x = "Attainable yield (ton/ha)",
       y = "Damage coefficient (%/p.p)")+
  theme_bw()+
    theme(
    legend.position = "right",
    text = element_text(size = 14),
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 14,face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    legend.key.height = unit(1, "cm"),
    legend.title = element_text(size = 14, vjust = 0.5)
  )+
  scale_x_continuous(breaks = seq(4000, 16000, by = 4000),
                     expand = c(0.02,0.02)) +
  scale_y_continuous(breaks = seq(0.0, 0.20, by = 0.05),
                     expand = c(0.02,0.02))

rainbow_dc
```


## Group 1

```{r}

library(dplyr)
library(tidyr)

set.seed(123)

b0_sim = seq(4000, 16000,length.out = 400)

#b1_sim <- runif(400,min = 567.31, max = 796.82)
#b1_sim <- runif(400,min = 192.59, max = 376.04)

b1_sim <- runif(400,min = 159.97, max = 430.21)

n <- 50000

S_seq <- 0:9


sim_df_g1 <- expand_grid(
    S = S_seq,
    b0 = b0_sim,
    b1 = b1_sim
) %>%
  mutate(
    Y  = b0 + b1 * S,
    Y0 = b0
  )

sim_df_g1$group = "Group 1"
```

## Group 2

```{r}

library(dplyr)
library(tidyr)

set.seed(123)

b0_sim = seq(4000, 16000,length.out = 400)

#b1_sim <- runif(400,min = 567.31, max = 796.82)
#b1_sim <- runif(400,min = 192.59, max = 376.04)

b1_sim <- runif(400,min = 192.59, max = 376.04)


n <- 50000

S_seq <- 0:9


sim_df_g2 <- expand_grid(
    S = S_seq,
    b0 = b0_sim,
    b1 = b1_sim
) %>%
  mutate(
    Y  = b0 + b1 * S,
    Y0 = b0
  )

sim_df_g2$group = "Group 2"
```

## Group 3

```{r}

library(dplyr)
library(tidyr)

set.seed(123)

b0_sim = seq(4000, 16000,length.out = 400)

#b1_sim <- runif(400,min = 567.31, max = 796.82)
#b1_sim <- runif(400,min = 192.59, max = 376.04)

b1_sim <- runif(400,min = 567.31, max = 796.82)


n <- 50000

S_seq <- 0:9


sim_df_g3 <- expand_grid(
    S = S_seq,
    b0 = b0_sim,
    b1 = b1_sim
) %>%
  mutate(
    Y  = b0 + b1 * S,
    Y0 = b0
  )

sim_df_g3$group = "Group 3"
```

```{r}
sim_df_all = rbind(sim_df_g1,sim_df_g2,sim_df_g3)
```
```{r}

sim_df_all = sim_df_all %>% 
   group_by(group) %>% 
   mutate(pressure = case_when(b1 > median(b1) ~ "High pressure",
                           b1 <= median(b1) ~"Low pressure"))

simu_DC <- sim_df_all %>%
  group_by(group,pressure) %>%
  mutate(
    B0 = b0,
  DC = b1 / b0,
  B1 = b1)
```

```{r}

freq_dc = simu_DC %>% 
  ggplot(aes(DC))+
  geom_histogram(color = "white", bins = 15,fill = "black")+
  facet_wrap(~group, ncol = 1)+
   labs(x = "Damage coefficient (%/p.p)",
       y = "Frequency")+
  theme_bw()+
    theme(
    text = element_text(size = 14),
    legend.margin = margin(t = 0, r = 20, b = 0, l = 0),  # Aumenta a margem à direita da legenda
    strip.text = element_text(size = 14,face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    strip.background = element_blank())
```

```{r}

freq_dc | rainbow_dc

```

```{r}
ggsave("fig/DC.png", bg = "white", dpi = 600, height = 6, width = 10)

```

# Relative yield

## Group 1

```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 1467)
b1 <- runif(100,min = 159.9782, max = 430.2115)
b0 = runif(100,min =  6680.5477,max = 15566.8496)


df_r1 <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_r1$yield = b0 - b1*df_r1$sev - rep(u_j, each = 101)
df_r1$relative <- df_r1$yield *100 / b0
```
```{r}

summary(model_r1)
confint(model_r3)

```

```{r, warning=FALSE, message=FALSE}
regression_r1 = data_r1 |> 
 ggplot(aes(SB, y = kg_ha)) +
  geom_point(color = "NA")+
   scale_y_continuous(breaks = c(4000,6000,8000,10000,12000,14000,16000), 
                     limits = c(4000, 16000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
  geom_abline(aes(intercept = 11142.94 ,slope = -292.80),
              size = 2, fill = "#7FBF7B", color = "#7FBF7B")+
  
  geom_abline(aes(intercept = 6680.5477,slope = -430.2115) ,
              size = 1, linetype = 2, fill = "#7FBF7B", color = "#7FBF7B")+
  
  geom_abline(aes(intercept = 15566.8496,slope = -159.9782),
              size = 1, linetype = 2, fill = "#7FBF7B", color = "#7FBF7B")+
 # annotate("text", x = 6, y = 14000, label = "CL111", color = "black", size = 5) +
  #annotate("text", x = 6, y = 13500, label = "DC = 3.25", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        title = element_text(face = "bold"),
        axis.text.y = element_text(size = 12),
        legend.position = "none")+
  labs(x = "SB index", y = "Yield (kg/ha)")

regression_r1
```

```{r}
df_loss_r1 = df_r1 |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33_r1 = df_loss_r1 |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_r1 = data33_r1  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#7FBF7B")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,100))+
  #annotate("text", x = 1.80, y = 53, label = "CL111", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 3.25", color = "black", size = 5) +
  labs(x = "SB index",
       y = "Relative yield loss (%)",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12),
        #axis.text.y = element_blank(),
        title = element_text(face = "bold"))

RYL_r1


loss_r1 = df_loss_r1 |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "#7FBF7B")+
  theme_bw()+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,100),
                     breaks = c(0,20, 40, 60, 80, 100))+
  labs(x = "Relative yield loss (%)",
       y = "Frequency")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12),
        title = element_text(face = "bold"))


max(loss_r1$l)
min(loss_r1$l)
mean(loss_r1$l)
median(loss_r1$l)


```

## Group 2



```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 1679)
b1 <- runif(100,min = 111.386, max = 300.0809)
b0 = runif(100,min =  7734.8070,max = 11609.306)
#b1 <- rnorm(100,mean = 252, sd = 66)
#mean_uj = mean(u_j)



df_r2 <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_r2$yield = b0 - b1*df_r2$sev - rep(u_j, each = 101)
df_r2$relative <- df_r2$yield *100 / b0
```


```{r}
df_loss_r2 = df_r2 |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33_r2 = df_loss_r2 |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_r2 = data33_r2  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#D1BE91")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,100))+
  #annotate("text", x = 1.80, y = 53, label = "CLJ01", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 3.64", color = "black", size = 5) +
  #scale_color_colorblind()+
  labs(x = "SB index",
       y = "",
       color = "")+
  theme(text = element_text(size = 12),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))

RYL_r2


loss_r2 = df_loss_r2 |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "#D1BE91")+
  theme_bw()+
scale_x_continuous(expand = c(0, 0),
                     limits = c(0,100),
                     breaks = c(0,20, 40, 60, 80, 100))+
  labs(x = "Relative yield loss (%)",
       y = "")+
  theme(text = element_text(size = 12),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))


df_loss2_r2 = df_loss_r2 |> 
  filter(!sev == 0) %>% 
  filter(l >0) 

max(df_loss2_r2$l)
min(df_loss2_r2$l)
mean(df_loss2_r2$l)
median(df_loss2_r2$l)

```

```{r}

summary(model_r2)
confint(model_r2)

```

```{r, warning=FALSE, message=FALSE}
regression_r2 = data222 |> 
 ggplot(aes(SB, y = kg_ha)) +
  geom_point(color = "NA")+
   scale_y_continuous(breaks = c(4000,6000,8000,10000,12000,14000,16000), 
                     limits = c(4000, 16000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
  geom_abline(aes(intercept = 9692.06, slope = -206.01),
              size = 2, fill = "#D1BE91", color = "#D1BE91")+
  geom_abline(aes(intercept = 7734.8070,slope = -300.0809) ,
              size = 1, linetype = 2, fill = "#D1BE91", color = "#D1BE91")+
  geom_abline(aes(intercept = 11609.306,slope = -111.386),
              size = 1, linetype = 2, fill = "#D1BE91", color = "#D1BE91")+
 # annotate("text", x = 6, y = 14000, label = "CLJ01", color = "black", size = 5) +
  #annotate("text", x = 6, y = 13500, label = "DC = 3.64", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "SB index", y = " ")


regression_r2

```

## Group 3



```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 778.0)
b1 <- runif(100,min = 567.3166, max = 796.8269)
b0 = runif(100,min =  9344.7371,max = 15389.1507)
#b1 <- rnorm(100,mean = 252, sd = 66)
#mean_uj = mean(u_j)

df_r3 <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_r3$yield = b0 - b1*df_r3$sev - rep(u_j, each = 101)
df_r3$relative <- df_r3$yield *100 / b0
```

```{r}
df_loss_r3 = df_r3 |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33_r3 = df_loss_r3 |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_r3 = data33_r3  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#A6764D")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,100))+
  #annotate("text", x = 1.87, y = 53, label = "Hybrids", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 2.59", color = "black", size = 5) +
  #scale_color_colorblind()+
  labs(x = "SB index",
       y = "",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))

RYL_r3


loss_r3 = df_loss_r3 |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "#A6764D")+
  theme_bw()+
scale_x_continuous(expand = c(0, 0),
                     limits = c(0,100),
                     breaks = c(0,20, 40, 60, 80, 100))+
  labs(x = "Relative yield loss (%)",
       y = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))

max(loss_r3$l)
min(loss_r3$l)
mean(loss_r3$l)
median(loss_r3$l)
```

```{r}
summary(model_r3)
confint(model_r3)
```

```{r, warning=FALSE, message=FALSE}
regression_r3 = data222 |> 
 ggplot(aes(SB, y = kg_ha)) +
  geom_point(color = "NA")+
   scale_y_continuous(breaks = c(4000,6000,8000,10000,12000,14000,16000), 
                     limits = c(4000, 16000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8),
                    limits = c(0, 8))+
  geom_abline(aes(intercept = 12368.25, slope = -682.34),
              size = 2, fill = "#A6764D", color = "#A6764D")+
  geom_abline(aes(intercept = 9344.7371,slope = -796.8269) ,
              size = 1, linetype = 2, fill = "#A6764D", color = "#A6764D")+
  geom_abline(aes(intercept = 15389.1507,slope = -567.3166),
              size = 1, linetype = 2, fill = "#A6764D", color = "#A6764D")+
  #annotate("text", x = 6, y = 14000, label = "Hybrids", color = "black", size = 5) +
  #annotate("text", x = 6, y = 13500, label = "DC = 2.59", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none",
    axis.text.y = element_blank())+
  labs(x = "SB index", y = " ")

regression_r3
```

```{r}
(regression_r1|regression_r2|regression_r3)/(RYL_r1|RYL_r2|RYL_r3)/(loss_r1|loss_r2|loss_r3)


ggsave("fig/loss_all.png", dpi = 600, bg = "white", height = 6, width = 9)
```

```{r}
SB_year = data222 %>% 
  ggplot(aes(SB))+
  geom_histogram(bins = 10, color = "white", fill = "#A6764D")+
  facet_wrap(~year)+
    theme_bw()+
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        title = element_text(face = "bold"),
        strip.background = element_blank(),
        strip.text = element_blank())+
  labs(x = "SB index", y = "Frequency")


yield_year = data222 %>% 
  ggplot(aes(kg_ha))+
  geom_histogram(bins = 10, color = "white", fill = "#2E8B57")+
  facet_wrap(~year)+
    theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        title = element_text(face = "bold"),
        strip.background = element_blank(),
        strip.text = element_text(size = 12, face = "bold"))+
  labs(x = "Yield (kg/ha)", y = "Frequency")

yield_year / SB_year

ggsave("fig/SB_yield.png", dpi = 600, bg = "white", height = 6, width = 9)
```

```{r}
f_r1 = data_r1
f_r1$group = "Group 1"

f_r2 = data_r2
f_r2$group = "Group 2"

f_r3 = data_r3
f_r3$group = "Group 3"

f_all = rbind(f_r1,f_r2,f_r3)

SB_genotypes = f_all %>% 
  ggplot(aes(SB))+
  geom_histogram(bins = 10, color = "white", fill = "#A6764D")+
  facet_wrap(~group, ncol = 3)+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
    theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        title = element_text(face = "bold"),
        strip.background = element_blank(),
        strip.text = element_blank())+
  labs(x = "SB index", y = "Frequency")


yield_genotypes = f_all %>% 
  ggplot(aes(kg_ha))+
  geom_histogram(bins = 10, color = "white", fill = "#2E8B57")+
  facet_wrap(~group, ncol = 3)+
    theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        title = element_text(face = "bold"),
        strip.background = element_blank(),
        strip.text = element_text(size = 12, face  = "bold"))+
  labs(x = "Yield (kg/ha)", y = "Frequency")

yield_genotypes / SB_genotypes

ggsave("fig/SB_yield_genotypes.png", dpi = 600, bg = "white", height = 6, width = 9)
```



