---
title: ""
message: false
warning: false
---


# Packages

```{r}
library(dplyr)
library(gsheet)
library(tidyverse)
library(writexl)
library(patchwork)
library(minpack.lm)
gc()
```

# Importation

```{r, warning=FALSE, message=FALSE}
data = gsheet2tbl("https://docs.google.com/spreadsheets/d/18U2-FRdO9PdUdFYayHW0oFo_uE92nSgnvtxRyHt1SXQ/edit?usp=sharing")
```

```{r, warning=FALSE, message=FALSE}
data2 = gsheet2tbl("https://docs.google.com/spreadsheets/d/1NZJYstoltlN18XhS1g4Om6laTYnHCgqwdiJ-GutUaYk/edit?usp=sharing")
data2
```

## 2022

```{r, eval=FALSE}
data22 = data %>%
  mutate(
    trt = factor(trt), 
         weig_12 = plot_w*((100-moist)/88), 
         yld = weig_12/(80/43560), 
         kg_ha = yld*1.2085)

#write_xlsx(data22,"data/data22.xlsx")
```

## 2023

```{r, eval=FALSE}
data23 = data2 %>%
  filter(year == 2023) %>% 
  mutate(
    trt = factor(trt), 
         #weig_12 = TW*((100-moist)/88), 
         yld = weight/(80/43560), 
         kg_ha = yld*1.2085)


#write_xlsx(data23,"data/data23.xlsx")
```

## 2024

```{r, eval=FALSE}
data24 = data2 %>%
  filter(year == 2024) %>% 
  mutate(
    trt = factor(trt), 
         #weig_12 = TW*((100-moist)/88), 
         yld = weight/(80/43560), 
         kg_ha = yld*1.2085)


#write_xlsx(data24,"data/data24.xlsx")
```

## 2025

```{r, eval=FALSE}
data25 = data2 %>%
  filter(year == 2025) %>% 
  mutate(
    trt = factor(trt), 
         #weig_12 = TW*((100-moist)/88), 
         yld = weight/(80/43560), 
         kg_ha = yld*1.2085)


#write_xlsx(data25,"data/data25.xlsx")
```

```{r}
sb_ipm = data2
```

# Damage function

## Linear regression

```{r, warning=FALSE, message=FALSE}
sb_ipm_d <- sb_ipm %>%
  group_by(year,trt,gen,fung,time,head) %>%
  summarise(
    yield = mean(yield, na.rm = TRUE),
    SB = mean(SB2, na.rm = TRUE),
    .groups = "drop"
  )


head(sb_ipm_d)
```

```{r, warning=FALSE, message=FALSE}

sb_ipm_d2 <- data2 %>%
  group_by(year,trt,gen,fung,time) %>%
  summarise(
    SB2 = mean(SB2, na.rm = TRUE),
    yield = mean(yield, na.rm = TRUE),
    .groups = "drop"
  )


cor.test(sb_ipm_d2$yield,sb_ipm_d2$SB2, method = "pearson")
```

```{r, warning=FALSE, message=FALSE}
sb_ipm_d %>% 
  ggplot(aes(SB, yield))+
  geom_point()+
  geom_smooth(method = "lm")

```

```{r, warning=FALSE, message=FALSE}
library(lme4)
sb_damage = lmer(yield ~ SB +(1|year), data = sb_ipm_d)

```

```{r, warning=FALSE, message=FALSE}
summary(sb_damage)
```

```{r, warning=FALSE, message=FALSE}
confint(sb_damage)
```

```{r, warning=FALSE, message=FALSE}
gen_summary = sb_ipm_d %>% 
  filter(time == "_CHECK") %>% 
  filter(!is.na(gen)) %>% 
  group_by(gen) %>% 
  summarise(
    yield = mean(yield),
    SB = mean(SB)
  )

gen_summary
```

```{r, eval = FALSE, echo=FALSE}
library(simr)
library(ggplot2)
library(dplyr)

# Ajuste do modelo original
sev_lmer <- lmer(yield ~ head + (1|year), data = sb_ipm_d)

# Criar um modelo extendido para simulação
ext_sev_lmer <- extend(sev_lmer, along = "head", n = 10000)

# Rodar várias simulações do powerCurve e armazenar os resultados
num_simulations <- 50  # Número de simulações individuais
power_results <- list()

for (i in 1:num_simulations) {
  power_results[[i]] <- as.data.frame(summary(powerCurve(ext_sev_lmer, 
                                                          along = "head", 
                                                          nsim = 100, 
                                                          breaks = 1:100)))
}


power_df <- bind_rows(power_results, .id = "simulation")

#write_xlsx(power_df, "data/power_df.xlsx")

gc()
```

```{r, warning=FALSE, message=FALSE}
overall_regression = sb_ipm_d |> 
 ggplot(aes(head, y = yield)) +
  geom_point(color = "NA")+
  scale_y_continuous(breaks = c(5000,6000,7000,8000,9000,
                      10000,11000,12000,13000,14000), 
                     limits = c(5000, 14000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8),
                    limits = c(0, 8))+
  geom_abline(aes(slope = -343.35, intercept = 10303.08),
              size = 2, fill = "black", color = "black")+
  geom_abline(aes(intercept = 8714.7951,slope = -447.9003) ,
              size = 1, linetype = 2)+
  geom_abline(aes(intercept = 11883.3816,slope = -239.0946), size = 1, linetype = 2)+
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "SB index", y = "Yield (kg/ha) ")

overall_regression
```

```{r, warning=FALSE, message=FALSE}

sb_ipm_hh = sb_ipm_d %>% 
  filter(!is.nan(SB))


mean(sb_ipm_hh$SB)
sd(sb_ipm_hh$SB)
median(sb_ipm_hh$SB)

Fx =environment(ecdf(sb_ipm_hh$SB))$y
x = environment(ecdf(sb_ipm_hh$SB))$x

slope_reg = nlsLM(Fx ~ pgamma(x, shape, rate,log = FALSE) ,
      start = c(shape = 2, rate = 1),
      control = nls.lm.control(maxiter = 1024))

summary(slope_reg)

sb_head = sb_ipm_d %>% 
  ggplot(aes(SB))+
 # geom_histogram(color = "white", fill = "orange3", bins = 15)+
  geom_histogram(aes(y = ..density..), fill = "#A6764D", color = "white", bins = 20) + #eab76f #6F3F1F
  #stat_function(fun = dnorm, args = list(mean = 2.52, sd = 2.11), 
   stat_function(fun=function(x) dgamma(x, 1.12686 , 0.44039),
               color = "black", size = 2, linetype = "dashed") + 
  theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "SB index", y = "Frequency")



mean(sb_ipm_d$yield)
sd(sb_ipm_d$yield)

sb_yield = ggplot(sb_ipm_d, aes(x = yield)) +
  geom_histogram(aes(y = ..density..), fill = "#2E8B57", color = "white", bins = 20) + ##08A045
  stat_function(fun = dnorm, args = list(mean = 9737.181, sd = 2821.136), 
                color = "black", size = 2, linetype = "dashed") + 
    theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "Yield (kg/ha) ", y = "Frequency")

#8AD



sb_head+sb_yield

```

```{r, warning=FALSE, message=FALSE}

library(ggplot2)
library(patchwork)
library(cowplot)


base_plot <- (sb_head / sb_yield | overall_regression) +
  plot_layout(guides = "collect") +
  plot_annotation(
    theme = theme(
      legend.position      = "top",
      legend.justification = "center",
      legend.box.just      = "center"
    )
  )


base_grob <- patchworkGrob(base_plot)



final_plot <- ggdraw(base_grob) +
  draw_plot_label(
    label = c("(a)", "(b)", "(c)"),
    x     = c(0, 0, 0.50), 
    y     = c(1, 0.5, 1),   
    size  = 14,                    
    fontface = "bold"
  )


final_plot

```

```{r, warning=FALSE, message=FALSE}
#(overall_regression)|sb_head/sb_yield

ggsave("fig/lm_yield_head.png", bg = "white", dpi = 600,height = 6, width = 10)
```

## Relative yield

```{r, warning=FALSE, message=FALSE}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 1410)
b1 <- runif(100,min = 239.0946, max = 447.9003)
#mean_uj = mean(u_j)

df <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df$yield = 10303 - b1*df$sev - rep(u_j, each = 101)
df$relative <- df$yield *100 / 10303



```

```{r, warning=FALSE, message=FALSE}
df = df %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))


df_summary <- df %>%
  filter(sev <=8) %>% 
  group_by(pressure) %>%
  summarise(
    mean_yield = mean(yield, na.rm = TRUE),
    se = sd(yield)/sqrt(n()),
    ci_low = quantile(yield, 0.025),
    ci_high = quantile(yield, 0.975),
    .groups = "drop"
  )

```

```{r, warning=FALSE, message=FALSE}


pressure_cols <- c(
  "High pressure"  = "#6F3F1F",
  "Low pressure" = "#2E8B57")

dodge_w <- 0.45 

interval = df %>% 
  filter(sev <= 8) %>% 
ggplot(aes(x = pressure, y = yield)) +
  geom_point(aes(color = pressure),
             position = position_jitter(width = 0.10),
             alpha = 0.03, size = 2, colour = "grey") +
  geom_pointrange(data = df_summary,
                  aes(x = pressure,
                      y = mean_yield,
                      ymin = ci_low,
                      ymax = ci_high,
                      color = pressure),
                  size = 1.1) +
    scale_y_continuous(limits = c(4000,16000),
                     breaks = c(4000,8000,12000,16000)) +
  #scale_color_brewer(palette = "Dark2") +
   scale_color_manual(values = pressure_cols) +
  geom_text(
    data = df_summary,
    aes(
      x     = pressure,
      y     = mean_yield,  # posiciona o rótulo próximo à ponta superior do IC
      # Opção 1 (base R):
      label = sprintf("%.2f", mean_yield),
      # Opção 2 (scales): label = number(mean_loss, accuracy = 0.01),
      color = pressure,
      group = pressure
    ),
    position   = position_dodge(width = dodge_w),
    nudge_x    = 0.08,    # -> direita (ajuste fino conforme seu espaçamento)
    nudge_y    = 0.08,       # pequeno empurrão para não colar na barra
    hjust      = -0.4,          # à direita; ajuste conforme preferir
    vjust      = 2,       # ligeiramente acima da ponta do intervalo
    size       = 5,
    fontface   = "bold.italic"
    #, check_overlap = TRUE   # opcional para evitar sobreposição
  )+
  theme_bw() +
  labs(x = "Pressure level",
       y = "Predicted yield (kg/ha)",
       color = "Pressure",
       fill = "Pressure")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")



interval


```

```{r, warning=FALSE, message=FALSE}
df2 = df %>% 
  group_by(sev) %>% 
  summarise(mean = mean(relative),
     up_95 = quantile(relative, 0.975),
     low_95 = quantile(relative, 0.025))
```

```{r, warning=FALSE, message=FALSE}
relative_plot = ggplot() +
  geom_line(data = df, aes(x = sev, y = relative, group = rep), 
            color = "grey", alpha = 0.4) +  # Linhas cinzas para cada simulação
  geom_line(data = df2, aes(x = sev, y = mean), 
            color = "black", size = 2) +  # Linha média
  geom_line(data = df2, aes(x = sev, y = up_95), 
            color = "black", linetype = "dashed",size = 1) +  # IC superior
  geom_line(data = df2, aes(x = sev, y = low_95), 
            color = "black", linetype = "dashed",size = 1) +  # IC inferior
  scale_y_continuous(breaks = c(20,30, 40,50, 60,
                                70,80,90,100), 
                     limits = c(20, 100),
                     expand = c(0, 2))+
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8),
                     limits = c(0, 8),
                     expand = c(0, 0))+
  coord_cartesian(xlim = c(0,8), ylim = c(20,100))+
  labs(x = "Head (%)", y = "Relative yield (%) ")+
  #geom_hline(yintercept = 87,
   #          linetype = 2, color = "darkblue", size = 1)+
  #geom_vline(xintercept = c(25), linetype = 2, color = "darkblue", size = 1)+
  theme_bw()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "SB head (%) ", y = "Relative yield (%) ")

relative_plot
```

```{r, warning=FALSE, message=FALSE}
mean(u_j)
sd(u_j)
df$u_j = u_j

residue = df %>% 
  ggplot(aes(u_j))+
 geom_histogram(aes(y = ..density..), fill = "#2E8B57", color = "white", bins = 20) + ##08A045  #5E8000
  stat_function(fun = dnorm, args = list(mean = 153.5312, sd = 1266.46), 
                color = "black", size = 2, linetype = "dashed") + 
    theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "Random effect (kg/ha) ", y = "Frequency")

residue
```

```{r, warning=FALSE, message=FALSE}
df_loss = df |>
  filter(sev <=8) %>% 
  mutate(l = 100*((10303- yield)/yield)) |> 
  filter(!is.na(l))

data33 = df_loss |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficient,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL = data33  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#A6764D")+
  theme_bw()+
  xlim(0,8)+
  ylim(0,100)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,8),
                     breaks = c(0,1,2,3,4,5,6,7,8)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,100))+
  #scale_color_colorblind()+
  labs(x = "SB index",
       y = "Relative yield loss (%)",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"))

RYL
```

```{r, warning=FALSE, message=FALSE}
base_plot <- (interval / residue | RYL) +
  plot_layout(guides = "collect") +
  plot_annotation(
    theme = theme(
      legend.position      = "top",
      legend.justification = "center",
      legend.box.just      = "center"
    )
  )


base_grob <- patchworkGrob(base_plot)



final_plot <- ggdraw(base_grob) +
  draw_plot_label(
    label = c("(a)", "(b)", "(c)"),
    x     = c(0, 0, 0.50), 
    y     = c(1, 0.5, 1),   
    size  = 14,                    
    fontface = "bold"
  )


final_plot

ggsave("fig/relative.png", bg = "white", dpi = 600,height = 6, width = 10)
```

## Boxplot

```{r, warning=FALSE, message=FALSE}



sb_ipm_d %>%
  filter(year != "2022") %>%
  ggplot(aes(x = reorder(gen, +yield), y = yield)) +
  # map size only here:
  geom_jitter(aes(size = as.numeric(SB),colour = as.numeric(SB)), width = 0.1, height = 0, alpha = 0.6) +
  geom_boxplot(width = 0.7, outlier.shape = NA) +  # keep boxplot size constant
    scale_color_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 4,             # number of steps (adjust for contrast)
    breaks = seq(0, 8, 2),
    name = "",
    
guide = guide_legend(
      override.aes = list(size = 6, shape = 16, alpha = 1),
      title.position = "top",
      ncol = 1, byrow = TRUE
    )
)+
  scale_size_continuous(name = "SB index",
                        range = c(1.5, 6),     # make the size differences obvious
                   breaks = c(0, 2, 4, 6,8),  # if these are typical head values
                        limits = c(0, 8)) +   # optional: clamp extremes
 
    theme_bw() +
  facet_wrap(~ time, ncol = 4) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust = 1),
        text = element_text(size = 12, face = "bold")) +
  labs(
    x = "Rice genotype",
    y = "Yield (kg/ha)")


ggsave("fig/boxplot.png", bg = "white", dpi = 600, height = 6 ,width = 10)
```

```{r, warning=FALSE, message=FALSE}
sb_ipm %>% 
  #filter(!year == "2022") %>% 
  #filter(time == "_CHECK") %>% 
  ggplot(aes(as.factor(year),yield))+
  geom_jitter(width = .1)+
  geom_boxplot()+
  ggthemes::theme_few()+
  theme(axis.text.x = element_text(angle = 45))
```
