---
title: "Inicio do Script (felipe.qmd) que escrevi para o Felipe com o yield. Esse script sera usado futuramente para o proximo artigo considerando o outro banco de dados com mais genotipos."
author: "1/13/2026"
format: html
editor: visual
---

# Packages

```{r}
library(dplyr)
library(gsheet)
library(tidyverse)
library(writexl)
library(patchwork)
library(minpack.lm)
gc()
```

```{r, warning=FALSE, message=FALSE}
data2 = gsheet2tbl("https://docs.google.com/spreadsheets/d/1NZJYstoltlN18XhS1g4Om6laTYnHCgqwdiJ-GutUaYk/edit?usp=sharing")
data2


```

```{r}
sb_ipm = data2
gc()
```

```{r, warning=FALSE, message=FALSE}
sb_ipm_d <- sb_ipm %>%
  filter(!trial == "25-P2S4_SB_IPM2") %>% 
  group_by(year,trt,gen,fung,time,tolerance,head) %>%
  summarise(
    yield = mean(yield, na.rm = TRUE),
    SB = mean(SB2, na.rm = TRUE),
    .groups = "drop"
  )

unique(sb_ipm_d$year)
head(sb_ipm_d)

sb_ipm %>% count(year, trial)
```

```{r}
sb_ipm_d %>% 
  filter(!is.na(tolerance)) %>% 
  ggplot(aes(SB,yield, color = tolerance, group = tolerance))+
  geom_point()+
  geom_smooth(method = "glm")
```

# Boxplot

```{r}
sb_ipm_d %>%
  mutate(tolerance = factor(tolerance, 
             levels = c("S","MS", "R"))) %>%
  #filter(year != "2022") %>%
  ggplot(aes(tolerance, y = yield)) +
  # map size only here:
  geom_jitter(aes(size = as.numeric(SB),colour = as.numeric(SB)), width = 0.1, height = 0, alpha = 0.6) +
  geom_boxplot(width = 0.7, outlier.shape = NA) +  # keep boxplot size constant
    scale_color_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 4,             # number of steps (adjust for contrast)
    breaks = seq(0, 8, 2),
    name = "",
    
guide = guide_legend(
      override.aes = list(size = 6, shape = 16, alpha = 1),
      title.position = "top",
      ncol = 1, byrow = TRUE
    )
)+
  scale_size_continuous(name = "SB index",
                        range = c(1.5, 6),     # make the size differences obvious
                   breaks = c(0, 2, 4, 6,8),  # if these are typical head values
                        limits = c(0, 8)) +   # optional: clamp extremes
 
    theme_bw() +
  facet_wrap(~ time, ncol = 4) +
  theme(axis.text.x = element_text(vjust = 0.9, hjust = 0.4),
        text = element_text(size = 12, face = "bold")) +
  labs(
    x = "Rice genotype",
    y = "Yield (kg/ha)")
```

```{r}
ggsave("fig/boxplot2.png", bg = "white", dpi = 600, height = 6 ,width = 10)
```

```{r}
sb_ipm_d %>% 
  ggplot(aes(SB))+
  geom_histogram(color = "white", bins = 15, fill = "#2E8B57")+
  facet_wrap(~time, ncol = 4)+
  theme_bw()
```

## CL111 - 2.64

```{r}
sb_ipm_d %>% 
 filter(year == "2022") %>%
  ggplot(aes(SB,yield))+
  geom_point()+
  geom_smooth(method = "lm")
```

```{r}

sb_ipm_s = sb_ipm_d %>% 
 filter(!year == "2022") %>% 
  #filter(!yield <5000) %>% 
  filter(tolerance == "S")

sb_ipm_s %>% 
  #filter(!year == "2022") %>%
  filter(tolerance == "S") %>% 
  ggplot(aes(SB,yield))+
  geom_point()+
  geom_smooth(method = "lm")

unique(sb_ipm_s$year)

```

```{r, warning=FALSE, message=FALSE}
library(lme4)
sb_damage_s = lmer(yield ~ SB+(1|year), data = sb_ipm_s) #+(1|year)
sb_damage_s1 = lm(yield ~ SB, data = sb_ipm_s)

AIC(sb_damage_s,sb_damage_s1)


summary(sb_damage_s1)
confint(sb_damage_s1)

cor.test(sb_ipm_s$yield,sb_ipm_s$SB)

```

```{r, warning=FALSE, message=FALSE}
overall_regression_s = sb_ipm_d |> 
 ggplot(aes(SB, y = yield)) +
  geom_point(color = "NA")+
   scale_y_continuous(breaks = c(5000,7000,9000,
                      11000,13000,15000), 
                     limits = c(5000, 15000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
  geom_abline(aes(slope = -365.78, intercept = 11204.31 ),
              size = 2, fill = "#7FBF7B", color = "#7FBF7B")+
  geom_abline(aes(intercept = 10764.6996,slope = -462.6471) ,
              size = 1, linetype = 2, fill = "#7FBF7B", color = "#7FBF7B")+
  geom_abline(aes(intercept = 11643.9244,slope = -268.9144),
              size = 1, linetype = 2, fill = "#7FBF7B", color = "#7FBF7B")+
  annotate("text", x = 6, y = 14000, label = "CL111", color = "black", size = 5) +
  annotate("text", x = 6, y = 13500, label = "DC = 3.25", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        axis.text.y = element_blank(),
        legend.position = "none")+
  labs(x = "SB index", y = "")

overall_regression_s
```

## CLJ01 = 2.93

```{r}

sb_ipm_d %>% 
  filter(tolerance == "MS") %>% 
  ggplot(aes(SB,yield))+
  geom_point()

sb_ipm_ms = sb_ipm_d %>% 
  #filter(!year == "2025") %>% 
  #filter(!yield <5000) %>% 
  filter(!yield >14000) %>% 
  filter(tolerance == "MS")

unique(sb_ipm_ms$year)

```

```{r, warning=FALSE, message=FALSE}
library(lme4)
sb_damage_ms = lmer(yield ~ SB +(1|year), data = sb_ipm_ms)#+(1|year)
sb_damage_ms1 = lm(yield ~ SB, data = sb_ipm_ms)

AIC(sb_damage_ms,sb_damage_ms1)


summary(sb_damage_ms1)
confint(sb_damage_ms1)

cor.test(sb_ipm_ms$yield,sb_ipm_ms$SB)

```

```{r, warning=FALSE, message=FALSE}
overall_regression_ms = sb_ipm_d |> 
 ggplot(aes(SB, y = yield)) +
  geom_point(color = "NA")+
   scale_y_continuous(breaks = c(5000,7000,9000,
                      11000,13000,15000), 
                     limits = c(5000, 15000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
  geom_abline(aes(slope = -342.67, intercept = 9370.03),
              size = 2, fill = "#D1BE91", color = "#D1BE91")+
  geom_abline(aes(intercept = 9001.8009,slope = -466.9204) ,
              size = 1, linetype = 2, fill = "#D1BE91", color = "#D1BE91")+
  geom_abline(aes(intercept = 9738.2550,slope = -218.4278),
              size = 1, linetype = 2, fill = "#D1BE91", color = "#D1BE91")+
  annotate("text", x = 6, y = 14000, label = "CLJ01", color = "black", size = 5) +
  annotate("text", x = 6, y = 13500, label = "DC = 3.64", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "SB index", y = "Yield (kg/ha) ")

overall_regression_ms

```

## Hybrids - 1.95

```{r}

sb_ipm_d %>% 
  filter(tolerance == "R") %>% 
  filter(!yield <10000) %>% 
  ggplot(aes(SB,yield))+
  geom_point()+
  geom_smooth(method = "lm")


sb_ipm_r = sb_ipm_d %>%
  #filter(!year == "2025") %>%
  #filter(!yield <10000) %>% 
  filter(tolerance == "R")


unique(sb_ipm_r$year)

```

```{r, warning=FALSE, message=FALSE}
library(lme4)
sb_damage_r = lmer(yield ~ SB+(1|year), data = sb_ipm_r)#+(1|year)
sb_damage_r1 = lm(yield ~ SB, data = sb_ipm_r)

AIC(sb_damage_r,sb_damage_r1)

summary(sb_damage_r1)
confint(sb_damage_r1)


cor.test(sb_ipm_r$yield,sb_ipm_r$SB)
```

```{r, warning=FALSE, message=FALSE}
overall_regression_r = sb_ipm_d |> 
 ggplot(aes(SB, y = yield)) +
  geom_point(color = "NA")+
  scale_y_continuous(breaks = c(5000,7000,9000,
                      11000,13000,15000), 
                     limits = c(5000, 15000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8),
                    limits = c(0, 8))+
  geom_abline(aes(slope = -357.02, intercept = 13773.58),
              size = 2, fill = "#A6764D", color = "#A6764D")+
  geom_abline(aes(intercept = 13493.7229,slope = -500.0758) ,
              size = 1, linetype = 2, fill = "#A6764D", color = "#A6764D")+
  geom_abline(aes(intercept = 14053.4451,slope = -213.9671),
              size = 1, linetype = 2, fill = "#A6764D", color = "#A6764D")+
  annotate("text", x = 6, y = 14000, label = "Hybrids", color = "black", size = 5) +
  annotate("text", x = 6, y = 13500, label = "DC = 2.59", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none",
    axis.text.y = element_blank())+
  labs(x = "SB index", y = " ")

overall_regression_r
```

# Histogram

```{r}

cores_tolerance <- c(
  "S"        = "#7FBF7B",
  "MS"      = "#D1BE91",
  "R"    = "#A6764D")
  


hist_index = sb_ipm_d %>%
  #filter(time == "_CHECK") %>%
  filter(!is.na(tolerance)) %>%
  mutate(tolerance = factor(tolerance, 
                            levels = c("MS", "S", "R"))) %>%
  ggplot(aes(SB, fill = tolerance)) +
  geom_histogram(color = "white", bins = 10) +
  facet_wrap(~tolerance, ncol = 3) +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
                    limits = c(0, 9))+
  #scale_fill_viridis_d(option = "D") +
  scale_fill_manual(values = cores_tolerance) +
  theme_bw() +
  labs(
    x = "SB index",
    y = "Frequency",
    fill = "Tolerance"
  ) +
  theme(
    legend.position = "none",
    text = element_text(size = 14, face = "bold"),
    strip.text = element_blank()
  )

hist_index
```

```{r}
cores_tolerance <- c(
  "S"        = "#7FBF7B",
  "MS"      = "#D1BE91",
  "R"    = "#A6764D")

hist_yield = sb_ipm_d %>%
  #filter(time == "_CHECK") %>% 
  filter(!is.na(tolerance)) %>%
  mutate(tolerance = factor(tolerance, 
                            levels = c("MS", "S", "R"))) %>%
  ggplot(aes(yield, fill = tolerance)) +
  geom_histogram(color = "white", bins = 10) +
  facet_wrap(~tolerance, ncol = 3) +
  #scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8,9),
   #                 limits = c(0, 9))+
  #scale_fill_viridis_d(option = "D") +
  scale_fill_manual(values = cores_tolerance) +
  theme_bw() +
  labs(
    x = "Yield (kg/ha)",
    y = "Frequency",
    fill = "Tolerance"
  ) +
  theme(
    legend.position = "none",
    text = element_text(size = 14, face = "bold"),
    strip.text = element_blank()
  )

hist_yield
```

```{r}
hist_index/hist_yield

ggsave("fig/hist_yld_idx.png", bg = "white", dpi = 600, width = 10, height = 6)
```

## Overall

```{r}

sb_ipm_overall = sb_ipm_d %>%
  filter(!year == "2022")


unique(sb_ipm_r$year)

```

```{r, warning=FALSE, message=FALSE}
library(lme4)
sb_damage_overall = lmer(yield ~ SB+(1|year), data = sb_ipm_overall)#+(1|year)
sb_damage_overall1 = lm(yield ~ SB, data = sb_ipm_overall)

AIC(sb_damage_overall,sb_damage_overall1)

summary(sb_damage_overall1)
confint(sb_damage_overall1)


cor.test(sb_ipm_r$yield,sb_ipm_r$SB)
```

```{r, warning=FALSE, message=FALSE}
overall_regression_overall = sb_ipm_d |> 
 ggplot(aes(SB, y = yield)) +
  geom_point(color = "NA")+
  scale_y_continuous(breaks = c(5000,7000,9000,
                      11000,13000,15000), 
                     limits = c(5000, 15000))+
 scale_x_continuous(breaks = c(0,1,2,3,4,5,6,7,8),
                    limits = c(0, 8))+
  geom_abline(aes(slope = -576.06, intercept = 12022.53),
              size = 2, fill = "black", color = "black")+
  geom_abline(aes(intercept = 11708.1034,slope = -669.9382) ,
              size = 1, linetype = 2, fill = "black", color = "black")+
  geom_abline(aes(intercept = 12336.9652,slope = -482.1847),
              size = 1, linetype = 2, fill = "black", color = "black")+
  annotate("text", x = 6, y = 14000, label = "Overall", color = "black", size = 5) +
  annotate("text", x = 6, y = 13500, label = "DC = 4.79", color = "black", size = 5) +
  #annotate(geom="text", x=55, y=6000, label="DC = 0.2",
   #           color="black", size = 4)+
  theme_bw()+
    #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none",
    axis.text.y = element_blank())+
  labs(x = "SB index", y = " ")

overall_regression_overall
```

```{r}
overall_regression_s+overall_regression_ms+overall_regression_r+overall_regression_overall
```

# Relative yield

## CL111

```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 821)
b1 <- runif(100,min = 268.9144, max = 462.6471 )
b0 = runif(100,min =  10764.6996,max = 11643.9244)
#b1 <- rnorm(100,mean = 252, sd = 66)
#mean_uj = mean(u_j)



df_sus <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_sus$yield = b0 - b1*df_sus$sev - rep(u_j, each = 101)
df_sus$relative <- df_sus$yield *100 / b0
```

```{r}
df_sus = df_sus %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))

df_sus$cultivar = "CL111"



df_summary_sus <- df_sus %>%
  filter(sev <=9) %>% 
  group_by(pressure) %>%
  summarise(
    mean_yield = mean(yield, na.rm = TRUE),
    se = sd(yield)/sqrt(n()),
    ci_low = quantile(yield, 0.025),
    ci_high = quantile(yield, 0.975),
    .groups = "drop"
  )

df_summary_sus$cultivar = "CL111"
```

```{r}
mean(u_j)
sd(u_j)
df_sus$u_j = u_j

residue_sus = df_sus %>% 
  ggplot(aes(u_j))+
 geom_histogram(aes(y = ..density..),
                fill = "#7FBF7B", color = "white", bins = 20) + ##08A045  #5E8000
  stat_function(fun = dnorm, args = list(mean = 89.39, sd = 737.4217), 
                color = "black", size = 2, linetype = "dashed") + 
    theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "Random effect (kg/ha) ", y = "Frequency")

residue_sus
```

```{r}
df_loss = df_sus |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33 = df_loss |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_sus = data33  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#7FBF7B")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,60))+
  #annotate("text", x = 1.80, y = 53, label = "CL111", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 3.25", color = "black", size = 5) +
  labs(x = "SB index",
       y = "",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))

RYL_sus


loss_sus = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "#7FBF7B")+
  theme_bw()+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,80),
                     breaks = c(0,10,20,30,40,50,60,70,80))+
  labs(x = "Yield loss (%)",
       y = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))


df_loss2 = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) 

max(df_loss2$l)
min(df_loss2$l)
mean(df_loss2$l)
median(df_loss2$l)


```

## CLJ01

```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 1024)
b1 <- runif(100,min = 218.4278, max = 466.9204)
b0 = runif(100,min =  9001.8009,max = 9738.2550)
#b1 <- rnorm(100,mean = 252, sd = 66)
#mean_uj = mean(u_j)


df_ms <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_ms$yield = b0 - b1*df_ms$sev - rep(u_j, each = 101)
df_ms$relative <- df_ms$yield *100 / b0
```

```{r}
df_ms = df_ms %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))

df_ms$cultivar = "CLJ01"

df_summary_ms <- df_ms %>%
  filter(sev <=9) %>% 
  group_by(pressure) %>%
  summarise(
    mean_yield = mean(yield, na.rm = TRUE),
    se = sd(yield)/sqrt(n()),
    ci_low = quantile(yield, 0.025),
    ci_high = quantile(yield, 0.975),
    .groups = "drop"
  )

df_summary_ms$cultivar = "CLJ01"
```

```{r}
mean(u_j)
sd(u_j)
df_ms$u_j = u_j

residue_ms = df_ms %>% 
  ggplot(aes(u_j))+
 geom_histogram(aes(y = ..density..),
                fill = "#D1BE91", color = "white", bins = 20) + ##08A045  #5E8000
  stat_function(fun = dnorm, args = list(mean = 111.5007, sd = 919.75), 
                color = "black", size = 2, linetype = "dashed") + 
    theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "Random effect (kg/ha) ", y = "Frequency")

residue_ms
```

```{r}
df_loss = df_ms |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33 = df_loss |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_ms = data33  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#D1BE91")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,60))+
  #annotate("text", x = 1.80, y = 53, label = "CLJ01", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 3.64", color = "black", size = 5) +
  #scale_color_colorblind()+
  labs(x = "SB index",
       y = "Relative yield loss (%)",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"))

RYL_ms


loss_ms = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "#D1BE91")+
  theme_bw()+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,80),
                     breaks = c(0,10,20,30,40,50,60,70,80))+
  labs(x = "Yield loss (%)",
       y = "Frequency")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"))


df_loss2 = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) 

max(df_loss2$l)
min(df_loss2$l)
mean(df_loss2$l)
median(df_loss2$l)

```

## Hybrids

```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 778.0)
b1 <- runif(100,min = 213.9671, max = 500.0758)
b0 = runif(100,min =  13493.7229,max = 14053.4451)
#b1 <- rnorm(100,mean = 252, sd = 66)
#mean_uj = mean(u_j)

df_res <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_res$yield = b0 - b1*df_res$sev - rep(u_j, each = 101)
df_res$relative <- df_res$yield *100 / b0
```

```{r}
df_res = df_res %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))


df_res$cultivar = "Hybrids"

df_summary_res <- df_res %>%
  filter(sev <=9) %>% 
  group_by(pressure) %>%
  summarise(
    mean_yield = mean(yield, na.rm = TRUE),
    se = sd(yield)/sqrt(n()),
    ci_low = quantile(yield, 0.025),
    ci_high = quantile(yield, 0.975),
    .groups = "drop"
  )

df_summary_res$cultivar = "Hybrids"
```

```{r}
mean(u_j)
sd(u_j)
df_res$u_j = u_j

residue_res = df_res %>% 
  ggplot(aes(u_j))+
 geom_histogram(aes(y = ..density..),
                fill = "#A6764D", color = "white", bins = 20) + ##08A045  #5E8000
  stat_function(fun = dnorm, args = list(mean = 84.71, sd = 698.79), 
                color = "black", size = 2, linetype = "dashed") + 
    theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "Random effect (kg/ha) ", y = "Frequency")

residue_res
```

```{r}
df_loss = df_res |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33 = df_loss |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_res = data33  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "#A6764D")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,60))+
  #annotate("text", x = 1.87, y = 53, label = "Hybrids", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 2.59", color = "black", size = 5) +
  #scale_color_colorblind()+
  labs(x = "SB index",
       y = "",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))

RYL_res


loss_res = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "#A6764D")+
  theme_bw()+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,80),
                     breaks = c(0,10,20,30,40,50,60,70,80))+
  labs(x = "Yield loss (%)",
       y = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))


df_loss2 = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) 

max(df_loss2$l)
min(df_loss2$l)
mean(df_loss2$l)
median(df_loss2$l)
```

## Overall

```{r}
set.seed(1)

u_j <- rnorm(100, mean = 0, sd = 1696.3)
b1 <- runif(100,min = 482.1847, max = 669.9382)
b0 = runif(100,min =  11708.1034,max = 12336.9652)


df_overall <- expand.grid(sev = seq(0, 100, by = 1), rep = 1:100)
df_overall$yield = b0 - b1*df_overall$sev - rep(u_j, each = 101)
df_overall$relative <- df_overall$yield *100 / b0
```

```{r}
df_overall = df_overall %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))

df_overall$cultivar = "Overall"

df_summary_overall <- df_overall %>%
  filter(sev <=9) %>% 
  group_by(pressure) %>%
  summarise(
    mean_yield = mean(yield, na.rm = TRUE),
    se = sd(yield)/sqrt(n()),
    ci_low = quantile(yield, 0.025),
    ci_high = quantile(yield, 0.975),
    .groups = "drop"
  )

df_summary_overall$cultivar = "Overall"
```

```{r}
mean(u_j)
sd(u_j)
df_overall$u_j = u_j

residue_overall = df_overall %>% 
  ggplot(aes(u_j))+
 geom_histogram(aes(y = ..density..),
                fill = "black", color = "white", bins = 20) + ##08A045  #5E8000
  stat_function(fun = dnorm, args = list(mean = 184.70, sd = 1523.61), 
                color = "black", size = 2, linetype = "dashed") + 
    theme_bw()+
  #ggthemes::theme_few()+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        title = element_text(face = "bold"),
        legend.position = "none")+
  labs(x = "Random effect (kg/ha) ", y = "Frequency")

residue_overall
```

```{r}
df_loss = df_overall |>
  filter(sev <=9) %>% 
  mutate(l = 100*((b0- yield)/b0)) |> 
  filter(!is.na(l))


data33 = df_loss |> 
  group_by(as.factor(rep)) |> 
  summarise(slope = lm(l~0+sev)$coefficients,
            vi = as.numeric(vcov(lm(l~0+sev))))


RYL_overall = data33  %>% 
  ggplot()+
  geom_abline(aes(intercept = 0, slope = slope), alpha = 0.9, color = "black")+
  theme_bw()+
  xlim(0,9)+
  ylim(0,60)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,9),
                     breaks = c(0,1,2,3,4,5,6,7,8,9)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0,60))+
  #annotate("text", x = 1.80, y = 53, label = "Overall", color = "black", size = 5) +
  #annotate("text", x = 2, y = 50, label = "DC = 4.79", color = "black", size = 5) +
  #scale_color_colorblind()+
  labs(x = "SB index",
       y = "",
       color = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))

RYL_overall


loss_overall = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) %>% 
  ggplot(aes(l))+
  geom_histogram(color = "white", bins = 10, fill = "black")+
  theme_bw()+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0,80),
                     breaks = c(0,10,20,30,40,50,60,70,80))+
  labs(x = "Yield loss (%)",
       y = "")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        axis.text.y = element_blank(),
        title = element_text(face = "bold"))


df_loss2 = df_loss |> 
  filter(!sev == 0) %>% 
  filter(l >0) 

max(df_loss2$l)
min(df_loss2$l)
mean(df_loss2$l)
median(df_loss2$l)
```

```{r}
(overall_regression_ms|overall_regression_s|overall_regression_r|overall_regression_overall)/(RYL_ms|RYL_sus|RYL_res|RYL_overall)/(loss_ms|loss_sus|loss_res|loss_overall)


ggsave("fig/loss_all.png", dpi = 600, bg = "white", width = 14, height = 10) #, height = 8
```

## Predicted yield

```{r}

df_all = rbind(df_sus,df_ms,df_res,df_overall)
df_summary_all = rbind(df_summary_sus,df_summary_ms,df_summary_res,
                       df_summary_overall)

df_summary_all = df_summary_all %>% 
mutate(cultivar = factor(cultivar, 
             levels = c("CLJ01","CL111", "Hybrids", "Overall")))
  

pressure_cols <- c(
  "High pressure"  = "#6F3F1F",
  "Low pressure" = "#2E8B57")

dodge_w <- 0.45 

interval_all = df_all %>% 
  mutate(cultivar = factor(cultivar, 
             levels = c("CLJ01","CL111", "Hybrids", "Overall"))) %>%
  filter(sev <= 9) %>% 
ggplot(aes(x = pressure, y = yield)) +
  geom_point(aes(color = pressure),
             position = position_jitter(width = 0.10),
             alpha = 0.03, size = 2, colour = "grey") +
  geom_pointrange(data = df_summary_all,
                  aes(x = pressure,
                      y = mean_yield,
                      ymin = ci_low,
                      ymax = ci_high,
                      color = pressure),
                  size = 1.1) +
    scale_y_continuous(limits = c(4000,16000),
                     breaks = c(4000,8000,12000,16000)) +
  #scale_color_brewer(palette = "Dark2") +
   scale_color_manual(values = pressure_cols) +
  geom_text(
    data = df_summary_all,
    aes(
      x     = pressure,
      y     = mean_yield,  # posiciona o rótulo próximo à ponta superior do IC
      # Opção 1 (base R):
      label = sprintf("%.1f", mean_yield),
      # Opção 2 (scales): label = number(mean_loss, accuracy = 0.01),
      color = pressure,
      group = pressure
    ),
    position   = position_dodge(width = dodge_w),
    nudge_x    = 0.08,    # -> direita (ajuste fino conforme seu espaçamento)
    nudge_y    = 0.08,       # pequeno empurrão para não colar na barra
    hjust      = -0.2,          # à direita; ajuste conforme preferir
    vjust      = -1,       # ligeiramente acima da ponta do intervalo
    size       = 4,
    fontface   = "bold.italic"
    #, check_overlap = TRUE   # opcional para evitar sobreposição
  )+
  theme_bw() +
  facet_wrap(~cultivar, ncol = 1)+
  labs(x = "Pressure level",
       y = "Predicted yield (kg/ha)",
       color = "Pressure",
       fill = "Pressure")+
  theme(text = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        strip.text = element_blank(),
        title = element_text(face = "bold"),
        legend.position = "none")



interval_all
```

# Economic losses

## CL111

```{r}

set.seed(123)
sev = seq(0, 9,length.out = 400)
yld = seq(4000, 16000,length.out = 400)
#b1 <- runif(100,min = 268.9144, max = 462.6471 )
price_rice <- runif(2, min = 300, max = 600)

combined_data <- expand.grid(sev = sev, yld = yld,price_rice = price_rice)


ylmer_simu_sus = combined_data %>% 
  mutate(loss =((((((365.78/11204.31)*sev)*100)*yld)/100)/1000)*price_rice)


ylmer_simu_sus$cultivar = "CL111"

ylmer_simu_sus = ylmer_simu_sus %>% 
  mutate(
    attainable = case_when(yld >11204.31 ~ "High yield",
                                 yld <= 11204.31 ~"Low yield"))

ylmer_simu_sus = ylmer_simu_sus %>%
mutate(loss_ec =((((((365.78/11204.31)*sev)*100)*yld)/100)/1000)) %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))


head(ylmer_simu_sus)
```

## CLJ01

```{r}
set.seed(123)
sev = seq(0, 9,length.out = 400)
yld = seq(4000, 16000,length.out = 400)
#b1 <- runif(100,min = 218.4278, max = 466.9204)
price_rice <- runif(2, min = 300, max = 600)

combined_data <- expand.grid(sev = sev, yld = yld,price_rice = price_rice)


ylmer_simu_ms = combined_data %>% 
  mutate(loss =((((((342.67/9370.03)*sev)*100)*yld)/100)/1000)*price_rice)

ylmer_simu_ms$cultivar = "CLJ01"


ylmer_simu_ms = ylmer_simu_ms %>% 
  mutate(
    attainable = case_when(yld >9370.03 ~ "High yield",
                                 yld <= 9370.03 ~"Low yield"))

ylmer_simu_ms = ylmer_simu_ms %>%
mutate(loss_ec =((((((342.67/9370.03)*sev)*100)*yld)/100)/1000)) %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))

head(ylmer_simu_ms)
```

## Hybrids

```{r}
set.seed(123)
sev = seq(0, 9,length.out = 400)
yld = seq(4000, 16000,length.out = 400)
#b1 <- runif(100,min = 218.4278, max = 466.9204)
price_rice <- runif(2, min = 300, max = 600)

combined_data <- expand.grid(sev = sev, yld = yld,price_rice = price_rice)


ylmer_simu_res = combined_data %>% 
  mutate(loss =((((((357.02/13773.58)*sev)*100)*yld)/100)/1000)*price_rice)

ylmer_simu_res$cultivar = "Hybrids"

ylmer_simu_res = ylmer_simu_res %>% 
  mutate(
    attainable = case_when(yld >13773.58 ~ "High yield",
                                 yld <= 13773.58 ~"Low yield"))

ylmer_simu_res = ylmer_simu_res %>%
mutate(loss_ec =((((((357.02/13773.58)*sev)*100)*yld)/100)/1000)) %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))

head(ylmer_simu_res)
```

## Overall

```{r}
set.seed(123)
sev = seq(0, 9,length.out = 400)
yld = seq(4000, 16000,length.out = 400)
#b1 <- runif(100,min = 218.4278, max = 466.9204)
price_rice <- runif(2, min = 300, max = 600)

combined_data <- expand.grid(sev = sev, yld = yld,price_rice = price_rice)


ylmer_simu_overall = combined_data %>% 
  mutate(loss =((((((576.06/12022.53)*sev)*100)*yld)/100)/1000)*price_rice)

ylmer_simu_overall$cultivar = "Overall"

ylmer_simu_overall = ylmer_simu_overall %>% 
  mutate(
    attainable = case_when(yld >12022.53 ~ "High yield",
                                 yld <= 12022.53 ~"Low yield"))

ylmer_simu_overall = ylmer_simu_overall %>%
mutate(loss_ec =((((((576.06/12022.53)*sev)*100)*yld)/100)/1000)) %>%
   mutate(pressure = case_when(sev > 1.7 ~ "High pressure",
                           sev <= 1.7 ~"Low pressure"))

head(ylmer_simu_overall)
```

```{r}
ylmer_all = rbind(ylmer_simu_sus,ylmer_simu_ms,ylmer_simu_res,ylmer_simu_overall)

gc()
```

```{r}
heat_loss = ylmer_all %>%
  mutate(cultivar = factor(cultivar, 
             levels = c("CLJ01","CL111", "Hybrids", "Overall"))) %>%
  ggplot(aes(sev, yld, fill = loss)) +
  geom_raster() +
  scale_x_continuous(breaks = seq(0, 9, by = 1)) +
  scale_y_continuous(breaks = seq(4000, 16000, by = 2000))+
  scale_fill_stepsn(
    colours = c("#2E8B57",   # dark brown
                "#7FBF7B",   # medium brown
                "#D1BE91",   # beige transition
                "#A6764D",   # light green
                "#6F3F1F"),  # dark green
    n.breaks = 5,             # number of steps (adjust for contrast)
    breaks = seq(0, 4000, 500),
    name = "L (USD/ha)",
    
guide = guide_colorsteps(
    keyheight = unit(150, "pt")   # << AQUI aumenta a altura da legenda
  )
) +
  
  theme_bw() +
  labs(
    y = "Attainable yield (kg/ha)",
    x = "SB index"
  ) +
  facet_wrap(~cultivar, ncol = 1)+
  theme(
    text = element_text(size = 14),
    axis.title = element_text(size = 20, face = "bold"),
    strip.text = element_blank(),#element_text(size = 14),
    axis.text.x = element_text(vjust = 1),
    legend.position = "right",
    panel.grid = element_blank()
  )
 
 heat_loss
 
 gc()
```

```{r}
ylmer_all2= ylmer_all


simu_summary <- ylmer_all2 %>%
  group_by(pressure,attainable,cultivar) %>%
  summarise(
    mean_loss = mean(loss_ec, na.rm = TRUE),
    ci_low = quantile(loss_ec, 0.025),
    ci_high = quantile(loss_ec, 0.975),
    .groups = "drop"
  )

pressure_cols <- c(
  "High pressure"  = "#6F3F1F",
  "Low pressure" = "#2E8B57")
```

```{r}
library(ggplot2)
library(dplyr)
library(scales)   

dodge_w <- 0.45   # mantenha o mesmo valor usado nas outras camadas

interval2 <- ylmer_all2 %>% 
  mutate(cultivar = factor(cultivar, 
           levels = c("CLJ01","CL111", "Hybrids", "Overall"))) %>%
  ggplot(aes(x = pressure, y = loss))+
  
  # Intervalos (médias + IC) lado a lado por attainable
  geom_pointrange(
    data = simu_summary,
    aes(
      x        = pressure,
      y        = mean_loss,
      ymin     = ci_low,
      ymax     = ci_high,
      color    = pressure,
      linetype = attainable,
      group    = attainable
    ),
    position = position_dodge(width = dodge_w),
    size = 1.0
  ) +
  
  
  # Texto da média alinhado ao seu respectivo intervalo (lado a lado)
  geom_text(
    data = simu_summary,
    aes(
      x     = pressure,
      y     = ci_high,  # posiciona o rótulo próximo à ponta superior do IC
      # Opção 1 (base R):
      label = sprintf("%.1f", mean_loss),
      # Opção 2 (scales): label = number(mean_loss, accuracy = 0.01),
      color = pressure,
      group = attainable
    ),
    position   = position_dodge(width = dodge_w),
    nudge_x    = 0.08,    # -> direita (ajuste fino conforme seu espaçamento)
    nudge_y    = 0.08,       # pequeno empurrão para não colar na barra
    hjust      = -0.1,          # à direita; ajuste conforme preferir
    vjust      = 0.1,       # ligeiramente acima da ponta do intervalo
    size       = 4,
    fontface   = "bold.italic"
    #, check_overlap = TRUE   # opcional para evitar sobreposição
  ) +
  
  # Escalas
  scale_color_manual(values = pressure_cols, name = "Pressure") +
  scale_linetype_manual(values = c("Low yield" = "solid", "High yield" = "dashed"),
                        name = "Attainable") +
  scale_shape_manual(values = c("Low yield" = 16, "High yield" = 17),
                     name = "Attainable") +
  
  theme_bw() +
  facet_wrap(~cultivar, ncol =1)+
  labs(
    x = "Pressure level",
    y = "Yield loss (ton/ha)"
  ) +
  theme(
    text = element_text(size = 14),
    axis.title = element_text(size = 20, face = "bold"),
    strip.text = element_blank(),
    title = element_text(face = "bold"),
    legend.position = "none",
    legend.box = "horizontal"
  )

interval2
```

```{r}
(interval_all)|(interval2)|(heat_loss)
```

```{r}
ggsave("fig/ec_losses.png", dpi = 600,
       bg = "white", width = 12, height = 10)
```

# Epiffiter

```{r}

logist_model <- sim_logistic(
  N = 100,
  y0 = 0.01,
  dt = 1,
  r = 0.075,#0.075 0.06
  alpha = 0.2,
  n = 7
)
```

```{r}
logist_plot = logist_model %>%
  filter(time <=50) %>% 
  ggplot(aes(time, y)) +
  geom_jitter(aes(time, random_y), size = 3,color = "gray", width = .1) +
  geom_line(size = 1) +
  theme_minimal()+
  labs(
    title = "Logistic",
    y = "Disease intensity",
    x = "Time"
  )
logist_plot



logist_model %>% 
  filter(time == 41)
```

## Across time

```{r}

library(dplyr)
library(ggplot2)
library(tidyr)

# ---- Dados do emmeans (contrastes por time) ----
emm_contr <- tibble::tribble(
  ~time,       ~contrast, ~estimate, ~lower.CL, ~upper.CL,
  "_CHECK",    "R - MS",   4992, 3960, 6024,
  "_CHECK",    "S - MS",   1183,  151, 2215,
  "_CHECK",    "S - R",   -3809,-4841,-2777,

  "B",         "R - MS",   5115, 4082, 6147,
  "B",         "S - MS",   1434,  402, 2467,
  "B",         "S - R",   -3680,-4712,-2648,

  "B+H",       "R - MS",   5202, 4169, 6234,
  "B+H",       "S - MS",   1351,  319, 2383,
  "B+H",       "S - R",   -3851,-4883,-2818,

  "H",         "R - MS",   5457, 4425, 6490,
  "H",         "S - MS",   1415,  382, 2447,
  "H",         "S - R",   -4043,-5075,-3010,

  "PD7",       "R - MS",   4732, 3700, 5764,
  "PD7",       "S - MS",   1480,  448, 2513,
  "PD7",       "S - R",   -3251,-4284,-2219,

  "PD7+B",     "R - MS",   4933, 3901, 5965,
  "PD7+B",     "S - MS",   1517,  484, 2549,
  "PD7+B",     "S - R",   -3416,-4449,-2384,

  "PD7+B+H",   "R - MS",   5104, 4071, 6136,
  "PD7+B+H",   "S - MS",   1293,  261, 2326,
  "PD7+B+H",   "S - R",   -3810,-4842,-2778,

  "PD7+H",     "R - MS",   4771, 3739, 5803,
  "PD7+H",     "S - MS",   1447,  415, 2480,
  "PD7+H",     "S - R",   -3324,-4356,-2291
)

# ---- Extrair tolerance do contraste ----
emm_contr <- emm_contr %>%
  mutate(tolerance = case_when(
    contrast == "R - MS" ~ "R vs MS",
    contrast == "S - MS" ~ "S vs MS",
    contrast == "S - R"  ~ "S vs R"
  ))

# ---- Ordenar níveis do time para manter sequência ----
emm_contr$time <- factor(emm_contr$time,
                         levels = c("_CHECK","PD7","B","H","B+H","PD7+B","PD7+H","PD7+B+H"))

emm_contr %>% 
  #filter(!time == "_CHECK") %>% 
ggplot( aes(x = estimate, y = time)) +
  geom_pointrange(aes(xmin = lower.CL, xmax = upper.CL), size = 0.8) +
  geom_point(size = 3, color = "black") +
  geom_text(aes(label = round(estimate, 0)), hjust = -0.3, size = 4) +
  facet_wrap(~tolerance, ncol = 4, scale = "free_x") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() +
  labs(x = "Difference", y = "Time") +
  theme(
    strip.text = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14),
    text = element_text(size = 14)
  )


emm_contr %>% 
  filter(tolerance == "S vs MS") %>% 
  ggplot(aes(estimate, as.factor(time), group = time))+
  geom_point()+
  geom_line()+
  facet_wrap(~tolerance)

```

```{r}
library(ggdist)
cores_gen <- c(
  "X1"      = "#2E8B57",
  "X2"      = "#D1BE91",
  "X3"  = "#6F3F1F")


library(dplyr)
library(ggplot2)

summary_gen_time <- summary_gen_time %>%
  mutate(tolerance = recode(tolerance,
                            "MS" = "CLJ01",
                            "S"  = "CL111",
                            "R"  = "Hybrids"),
         tolerance = factor(tolerance, levels = c("CLJ01", "CL111", "Hybrids")))

mean_profit <- mean_profit %>%
  mutate(tolerance = recode(tolerance,
                            "MS" = "CLJ01",
                            "S"  = "CL111",
                            "R"  = "Hybrids"),
         tolerance = factor(tolerance, levels = c("CLJ01", "CL111", "Hybrids")))

profit = summary_gen_time %>%
  ggplot() +
  geom_vline(xintercept = 0, color = "gray40") +
  stat_slab(aes(Net_hf_mean, spray, fill = spray, alpha = stat(x > 0))) +
  stat_pointinterval(
    aes(Net_hf_mean, spray, group = tolerance, colour = spray),
    position = position_dodge(width = .6, preserve = "single"),
    .width = c(0.75, 0.95),
    alpha = 0.8
  ) +
  geom_text(data = mean_profit,
            aes(m, spray, label = P, color = spray),
            position = position_dodge(),
            size = 4, vjust = -3, hjust = -0.3, angle = 0, fontface = "bold.italic") +
  scale_fill_manual(values = cores_gen, name = "") +
  scale_colour_manual(values = cores_gen, guide = "none") +
  scale_alpha_manual(values = c(0.2, .9), labels = c("Positive", "Negative")) +
  guides(alpha = "none",
         fill = guide_legend(nrow = 1, byrow = TRUE,
                             override.aes = list(alpha = 1))) +
  theme_bw() +
  facet_wrap(~ tolerance, ncol = 1) +
   scale_shape_manual(values = 16) +
  scale_shape_manual(values= 16)+
  theme(
    legend.position  = "none",
    legend.direction = "horizontal",
    legend.box       = "horizontal",
    legend.key.width = unit(16, "pt"),
    legend.spacing.x = unit(6, "pt"),
    text = element_text(size = 14),
    strip.text = element_text(size = 14, face = "bold"),
    #strip.background = element_rect(fill = "white", color = "black"),
    strip.background = element_blank(),
    axis.title = element_text(size = 20, face = "bold")
  ) +
  labs(x = "Profit (USD/ha)", y = "Time")

profit

```
